version: 2

models:
  - name: dim_region
    description: Regions of avocado growings
    columns:

      - name: id
        description: unique id
        tests:
          - unique
          - not_null
          - relationships:
              field: region_id
              to: ref('fct_avocado')

  - name: dim_year
    columns:

      - name: year
        tests:
          - accepted_values:
              values: ['2015',
                      '2016',
                      '2017',
                      '2018']
              quote: false
      
  - name: fct_avocado
    columns:
      - name: avg_price
        tests:
          - positive_value
