version: 2

sources:
  - name: ecommerce
    database: bigquery-public-data
    schema: thelook_ecommerce
    tables:
      - name: orders
        identifier: orders
      - name: users
        identifier: users
      - name: order_items
        identifier: order_items
      - name: products
        identifier: products