version: 2

sources:
  - name: avocado
    database: winter-cocoa-336514
    schema: avocado_data
    tables:
      - name: avocado_prices
        identifier: avocado_prices

  - name: ecommerce
    database: bigquery-public-data
    schema: thelook_ecommerce
    tables:
      - name: orders
        identifier: orders
      - name: users
        identifier: users
      - name: order_items
        identifier: order_items
      - name: products
        identifier: products